### ISSUE TITLE
Annoying IDE stuff

### ISSUE THREAD

**Issue by cthoyt** [scolby33/easy_config#19]
I don't like PyCharm saying I need to reimplement `__init__`... This is happening because there's a `raise NotImplementedError` in there so nobody accidentally calls it. Maybe it would be better to have `__init__` do the same thing load does, then call `super().__init__()` in the end?

I think you had a reason for doing this

<img width="623" alt="screen shot 2018-10-11 at 11 52 03 am" src="https://user-images.githubusercontent.com/5069736/46796122-26fb1d80-cd4c-11e8-90cf-99b510fada49.png">

**Comment by scolby33** [comment]
The dataclass decorator overrides the provided `__init__`. My reason for doing this was so you couldn't instantiate the base `EasyConfig` class or any of its subclasses that weren't actually dataclasses. I'm not sure how to fix this--obviously PyCharm can't be expected to figure out the metaclass magic I'm doing, but I really don't like the idea of having a valid `__init__` on a non-dataclass subclass. Even calling `EasyConfig.load` should be an error, whereas (e.g.) `GitlabConfig.load` isn't one.

**Comment by scolby33** [comment]
Raising `TypeError` instead might be a good option.
